api:
  misirka:
    http:
      enable: true
      bind: ':8811'
      prefix: ''
    ws:
      enable: true
      url: '/ws'
    doc:
      enable: true
      path: 'doc'
      html_path: 'doc.html'
  state_poll_interval_msec: 10000
  levels_poll_interval_msec: 100
ctl:
  port_device: '/dev/ttyACM0'
  use_db_levels: true
